---
- name: Exercicio 02 - Loop de 1 a 10
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Imprimir número de 1 a 10
      debug:
        msg: "Número: {{ item }}"
      with_sequence: start=1 end=10
