---
- name: Exercicio 01 - Handlers
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Criar arquivo de configuração
      copy:
        content: "Configuração inicial"
        dest: /tmp/config.txt
      notify: Reiniciar serviço

  handlers:
    - name: Reiniciar serviço
      debug:
        msg: "Serviço reiniciado com sucesso!"