---
- name: Instalar Apache
  ansible.builtin.package:
    name: apache2
    state: present
  notify: Reiniciar Apache

- name: Criar diretório do site
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Implantar página index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: Reiniciar Apache

- name: Implantar página whoami
  ansible.builtin.template:
    src: whoami.html.j2
    dest: /var/www/html/whoami.html
    mode: '0644'
  notify: Reiniciar Apache

- name: Implantar página 404.html
  ansible.builtin.template:
    src: 404.html.j2
    dest: /var/www/html/404.html
    mode: '0644'
  notify: Reiniciar Apache

- name: Configurar Apache
  ansible.builtin.template:
    src: apache.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    mode: '0644'
  notify: Reiniciar Apache

- name: Ativar site padrão
  ansible.builtin.command: a2ensite 000-default.conf
  args:
    creates: /etc/apache2/sites-enabled/000-default.conf
  notify: Reiniciar Apache

- name: Garantir que Apache está ativo e habilitado
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
