# playbook_ldap.yml
- name: Configurar OpenLDAP com OU TI e usu치rios
  hosts: dc-eu
  become: true

  vars:
    domain: techskills.org
    base_dn: "dc=techskills,dc=org"
    ou: "TI"
    users:
      - { name: alice, password: "SenhaForte1" }
      - { name: bob, password: "SenhaForte2" }

  tasks:
    - name: Instalar slapd e ldap-utils
      apt:
        name:
          - slapd
          - ldap-utils
        state: present

    - name: Configurar OU e usu치rios
      block:
        - name: Criar OU TI
          command: ldapadd -x -D "cn=admin,{{ base_dn }}" -w admin -f ou_ti.ldif
          args:
            creates: /etc/ldap/ou_ti.ldif

        - name: Adicionar usu치rios
          with_items: "{{ users }}"
          loop_control:
            loop_var: user
          block:
            - name: Criar arquivo LDIF para {{ user.name }}
              template:
                src: user.ldif.j2
                dest: "/tmp/{{ user.name }}.ldif"
            - name: Adicionar usu치rio {{ user.name }}
              command: ldapadd -x -D "cn=admin,{{ base_dn }}" -w admin -f "/tmp/{{ user.name }}.ldif"
